#SPDX-License-Identifier: MIT-0
---
# tasks file for user
- name: set user password
  user:
    name: "{{ item.user_name }}"
    password: "{{ item.user_password|default(default_user_password) }}"
    shell: /bin/bash
  loop: "{{ users }}"
  vars:
    user: "{{ item }}"

- name: add user to sudo group
  user:
    name: "{{ item.user_name }}"
    groups: sudo
    append: true
  loop: "{{ users }}"
  vars:
    user: "{{ item }}"
  when: 
  - item.user_sudo=="yes"
  
- name: edit sudoers for user
  community.general.sudoers:
    name: "{{ item.user_name }}"
    user: "{{ item.user_name }}"
    commands: "{{ item.user_sudoers }}"
    state: present
  loop: "{{ users }}"
  when: 
  - item.user_sudoers is defined

- name: Add SSH public keys
  ansible.posix.authorized_key:
    user: "{{ item.0.user_name }}"
    state: present
    key: "{{ lookup('file', item.1) }}"
  with_subelements:
    - "{{ users }}"
    - user_ssh_key
  when: 
  - item.1 is defined
